# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gemm < Formula
  desc ""
  homepage ""
  version "0.2.0"

  on_macos do
    on_intel do
      url "https://github.com/yken2257/gemm/releases/download/v0.2.0/gemm_Darwin_x86_64.tar.gz"
      sha256 "28c0cce237351db69573a8345ccca425835c5f4be160fb7e16304227d0c05e15"

      def install
        bin.install "gemm"
      end
    end
    on_arm do
      url "https://github.com/yken2257/gemm/releases/download/v0.2.0/gemm_Darwin_arm64.tar.gz"
      sha256 "1411a45c4cb936e5012a8fd7f915fcee917acef971ce5ad78bbfebe04e972ed7"

      def install
        bin.install "gemm"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/yken2257/gemm/releases/download/v0.2.0/gemm_Linux_x86_64.tar.gz"
        sha256 "218038233c951e7934396568f2283ef163f70f96caaef3661143e1c101c7f106"

        def install
          bin.install "gemm"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/yken2257/gemm/releases/download/v0.2.0/gemm_Linux_arm64.tar.gz"
        sha256 "431944a95ff98de770f833a337a90f85c53bd90c5bb721eac2f5ada231ded120"

        def install
          bin.install "gemm"
        end
      end
    end
  end
end
